### ISSUE TITLE
python 'AtlasView' object does not support item assignment

### ISSUE THREAD

**Issue by ericjcgalvez** [ghoresh11/sling#2]
Hello, 
Thank you for the nice tool,
Unfortunately, I was trying to run the workflow and it breaks in the grouping step.
I tested in different systems and also create a conda environment with the tools' specific dependencies:
`conda create -n sling_py27 python=2.7.13 anaconda`
`source activate sling_py27`
`conda install -c bioconda blast=2.6.0`
`conda install -c biocore hmmer`

`git clone https://github.com/ghoresh11/sling.git`
`cd sling`
`python setup.py install`
`cd ./example `
`nohup sling run ID1 ./genomes/ toxins --cpu 20 –ti -o ./OUT_TEST/ &`

There is an error in the grouping step in the script ./sling/group_by_operon.py line 318
“python 'AtlasView' object does not support item assignment”

 It seems that it is an index problem, This is what I found: 
[https://stackoverflow.com/questions/47283340/adding-edge-attribute-causes-typeerror-atlasview-object-does-not-support-item]
 
I changed in the line 318 of group_by_operon:
G[n][0]["cluster_id"] = cluster_id.
 
Running by steps it works by I restarted the workflow and it breaks again.
Could you please double check if you get the same issues by git or pip the version in this repository

Thanks a lot

**Comment by ghoresh11** [comment]
This is a networkx versions issue.
SLING works with networkx v1.11. I've updated the setup file to  install the correct version of networkx.
